import axios from 'axios'

# GET https://api.coinbase.com/v2/prices/spot?currency=USD

###
# GET https://api.coinbase.com/v2/prices/spot?currency=ETH


###

# GET  https://api.coinbase.com/v2/exchange-rates?currency=ETH

###
# GET https://api.coinbase.com/v2/prices/:currency_pair/spot

###
# curl https://api.coinbase.com/v2/prices/BTC-USD/spot

###
GET https://api.coinbase.com/v2/prices/WLUNA-USD/spot


###
# get all known pairs
get https://api.exchange.coinbase.com/products

###
# get currency info - coin names and tickers
https://api.exchange.coinbase.com/currencies